platform :ios, ‘8.0’
target ‘Core’ do
    pod ‘MBProgressHUD’
    pod ‘AFNetworking’
    pod ‘MJExtension‘
    pod ‘UMengAnalytics-NO-IDFA‘
    pod ‘UMengUShare/UI’
    pod ‘UMengUShare/Social/ReducedWeChat'
    pod ‘UMengUShare/Social/ReducedQQ'
    pod 'MJRefresh'
#    pod 'SVProgressHUD'
    pod ‘AliyunOSSiOS’, ‘~> 2.6.0’
    pod 'UMessage', :podspec => 'https://raw.githubusercontent.com/kkme/UMessage/master/UMessage.podspec'
    pod 'JMessage'
    
    pod 'CocoaLumberjack'
    pod 'GPUImage', '~> 0.1.7'
    pod 'YYKit'

    pod 'Masonry'
    pod 'DZNEmptyDataSet'
    pod 'UITableView+FDTemplateLayoutCell'   
    pod 'FDFullscreenPopGesture'
    pod 'IQKeyboardManager'
    pod 'Reachability'
    pod 'SDCycleScrollView'
    
end
